---
version: "2"
services:
  code:
    build:
      context: .
      dockerfile: "Dockerfile-code"
    volumes:
      - ./src:/code

  data:
    image: cogniteev/echo
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
      - ./data/static:/static
      - ./data/media:/media
      - ./data/fluentd/log:/fluentd/log
      - ./data/elasticsearch:/usr/share/elasticsearch/data
      - ./data/nginx/log:/var/log/nginx

  pgsql:
    image: postgres
    depends_on:
      - data
    environment:
      - POSTGRES_DB=app_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "127.0.0.1:8032:5432"
    volumes_from:
      - data

  redis:
    image: redis

  elasticsearch:
    build: ./deploy/elasticsearch/
    ports:
      - "127.0.0.1:8020:9200"
      - "127.0.0.1:8030:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    depends_on:
      - data
    volumes_from:
      - data

  logstash:
    build: ./deploy/logstash/
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./deploy/logstash/config:/etc/logstash/conf.d
    ports:
      - "127.0.0.1:8050:5000"
      - "127.0.0.1:8012:12201/udp"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch

  kibana:
    build: ./deploy/kibana/
    volumes:
      - ./deploy/kibana/config/:/etc/kibana/
    ports:
      - "127.0.0.1:8056:5601"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch

  django:
    build:
      context: .
      dockerfile: "Dockerfile-dev"
    depends_on:
      - data
      - pgsql
      - redis
      - elasticsearch
      - logstash
    ports:
      - "127.0.0.1:8000:8000"
      - "127.0.0.1:8001:8001"
      - "127.0.0.1:8022:22"
    environment:
      - DEV=1
      - DEBUG=1
      - DJANGO_DATABASE_ENGINE=django.db.backends.postgresql_psycopg2
      - DJANGO_DATABASE_HOST=pgsql
      - DJANGO_DATABASE_NAME=app_db
      - DJANGO_DATABASE_USER=user
      - DJANGO_DATABASE_PASSWORD=password
#      - DJANGO_FLUENTD_HOST=fluentd
      - DJANGO_LOGSTASH_HOST=logstash
      - DJANGO_LOGSTASH_PORT=5000
    volumes_from:
      - code
      - data
    links:
      - pgsql
      - redis
      - elasticsearch
      - logstash
  nginx:
    depends_on:
      - data
      - django
    image: nginx
    ports:
      - "127.0.0.1:8080:80"
    logging:
      driver: gelf
      options:
        gelf-address: udp://127.0.0.1:8012
        tag: nginx
    volumes_from:
      - data
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - django
