---
version: "2"
services:
  data:
    build:
      context: .
      dockerfile: ./deploy/data/Dockerfile
  elasticsearch:
    build:
      context: .
      dockerfile: ./deploy/elasticsearch/Dockerfile
  logstash:
    build:
      context: .
      dockerfile: ./deploy/logstash/Dockerfile
  kibana:
    build:
      context: .
      dockerfile: ./deploy/kibana/Dockerfile
  django:
    build:
      context: .
      dockerfile: ./deploy/django/Dockerfile

  nginx:
    build:
      context: .
      dockerfile: ./deploy/nginx/Dockerfile

  prometheus:
    image:
      prom/prometheus
    volumes:
      - ./deploy/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    network_mode: host

  grafana:
    image:
      grafana/grafana

  storage:
    image: openzipkin/zipkin-mysql
    container_name: mysql

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    environment:
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=elasticsearch:9200
    ports:
      - 9411:9411
    depends_on:
      - storage

  dependencies:
    image: openzipkin/zipkin-dependencies
    container_name: dependencies
    entrypoint: crond -f
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=mysql
      - MYSQL_USER=zipkin
      - MYSQL_PASS=zipkin
    depends_on:
      - storage