---
version: "2"
services:
  data:
    build:
      context: .
      dockerfile: ./deploy/data/Dockerfile
  elasticsearch:
    build:
      context: .
      dockerfile: ./deploy/elasticsearch/Dockerfile
  logstash:
    build:
      context: .
      dockerfile: ./deploy/logstash/Dockerfile
  kibana:
    build:
      context: .
      dockerfile: ./deploy/kibana/Dockerfile
  django:
    build:
      context: .
      dockerfile: ./deploy/django/Dockerfile
    # network_mode: host

  # django:
  #   build:
  #     context: .
  #     dockerfile: ./deploy/django/Dockerfile
  # django2:
  #   build:
  #     context: .
  #     dockerfile: ./deploy/django2/Dockerfile
  nginx:
    build:
      context: .
      dockerfile: ./deploy/nginx/Dockerfile

  prometheus:
    image:
      prom/prometheus
    volumes:
      - ./deploy/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    network_mode: host
    # build:
    #   context: .
    #   dockerfile: ./deploy/prometheus/Dockerfile
  grafana:
    image:
      grafana/grafana
  
  storage:
    image: openzipkin/zipkin-mysql
    container_name: mysql
    # Uncomment to expose the storage port for testing
    # ports:
    #   - 3306:3306

  # The zipkin process services the UI, and also exposes a POST endpoint that
  # instrumentation can send trace data to. Scribe is disabled by default.
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    # Environment settings are defined here https://github.com/openzipkin/zipkin/tree/1.19.0/zipkin-server#environment-variables
    environment:
      - STORAGE_TYPE=mysql
      # Point the zipkin at the storage backend
      - MYSQL_HOST=mysql
      # Uncomment to enable scribe
      # - SCRIBE_ENABLED=true
      # Uncomment to enable self-tracing
      # - SELF_TRACING_ENABLED=true
      # Uncomment to enable debug logging
      # - JAVA_OPTS=-Dlogging.level.zipkin=DEBUG -Dlogging.level.zipkin2=DEBUG
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411
      # Uncomment if you set SCRIBE_ENABLED=true
      # - 9410:9410
    depends_on:
      - storage

  # Adds a cron to process spans since midnight every hour, and all spans each day
  # This data is served by http://192.168.99.100:8080/dependency
  #
  # For more details, see https://github.com/openzipkin/docker-zipkin-dependencies
  dependencies:
    image: openzipkin/zipkin-dependencies
    container_name: dependencies
    entrypoint: crond -f
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=mysql
      # Add the baked-in username and password for the zipkin-mysql image
      - MYSQL_USER=zipkin
      - MYSQL_PASS=zipkin
      # Uncomment to see dependency processing logs
      # - ZIPKIN_LOG_LEVEL=DEBUG
      # Uncomment to adjust memory used by the dependencies job
      # - JAVA_OPTS=-verbose:gc -Xms1G -Xmx1G
    depends_on:
      - storage